name: Run Euractiv Scraper

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 13 * * *'  # 13:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure npm auth (optional)
        run: |
          if [ -n "${NODE_AUTH_TOKEN}" ]; then
            echo "Configuring npm auth..."
            npm config set //registry.npmjs.org/:_authToken "${NODE_AUTH_TOKEN}"
            npm config delete always-auth || true
          else
            echo "No NPM token set; skipping auth config."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install deps
        run: npm install

      - name: Run the scraper
        run: |
          node MyScrapers/euractivJobs.js
          node MyScrapers/eurobrussels.js
          node MyScrapers/euRss.js
          node MyScrapers/euInstitutions.js
          node MyScrapers/jobsin.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OTHER_SECRET: ${{ secrets.OTHER_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
