name: Run Euractiv Scraper

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 13 * * *'  # 13:00 UTC
  workflow_dispatch:      # Allow manual runs too

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install

      - name: Run the scraper
        run: |
          node MyScrapers/euractivJobs.js
          node MyScrapers/eurobrussels.js
          node MyScrapers/euRss.js
          node MyScrapers/euInstitutions.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OTHER_SECRET: ${{ secrets.OTHER_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
