name: Run Euractiv Scraper

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 13 * * *'  # 13:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          standalone: true   # avoids registry fetch during setup

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run the scraper
        run: |
          node MyScrapers/euractivJobs.js
          node MyScrapers/eurobrussels.js
          node MyScrapers/euRss.js
          node MyScrapers/euInstitutions.js
          node MyScrapers/jobsin.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OTHER_SECRET: ${{ secrets.OTHER_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
